const mongo = require('./mongo');

mongo.loadCSV('RGJJUCxEYlBvcnQsRGJFbmdpbmUsRGJOYW1lLERiVXNlck5hbWUsRGJQYXNzd29yZCxEYlByZWZpeFRhYmxlLERiU3RydWN0dXJlCjAuMC4wLjAsODAsTmdpbngsdGVzdERCLHRlc3RVc2VyLHRlc3RQYXNzLCwieyIibmFtZSIiOnsiInR5cGUiIjoiInN0cmluZyIiLCIicmVxdWlyZWQiIjoiInRydWUiIn19IgoxMjcuMC4wLjEsNDQzLEFwYWNoZTIsdGVzdERCMix0ZXN0VXNlcjIsdGVzdFBhc3MyLHQsInsiImtleSIiOnsiInR5cGUiIjoiInN0cmluZyIiLCIicmVxdWlyZWQiIjoiInRydWUiIn19Igo=');
